---
# tasks file for kali

- name: Update kali base
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base applications
  apt: name={{ item }} state=present
  with_items:
    - emacs
    - vim