---
# tasks file for dvwa
- name: Download nodejs setups
  get_url:
    url:  https://deb.nodesource.com/setup
    dest: /tmp/nodesetup
    mode: 0755

- name: install node repos
  command: /tmp/nodesetup

- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Install base applications
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - curl
    - default-jre
    - default-jdk
    - build-essential
    - python2.7
    - python-dev
    - python-pip
    - ruby-full
    - git
    - lamp-server
    - nodejs
    - php-mysqli
    - php-gd
    - libapache2-mod-php
    - php

- apache2_module:
    state: present
    name: rewrite
- replace:
    path: /etc/apache2/sites-available/default
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
    backup: yes

- name: Restart service httpd, in all cases
  service:
    name: apache2
    state: restarted

- name: Reload service httpd, in all cases
  service:
    name: apache2
    state: reloaded

- name: Pull DVWA
  git:
    repo: 'https://github.com/ethicalhack3r/DVWA.git'
    dest: /var/www

- name: move the sample config to real config
  copy: remote_src=True src=/var/www/config/config.inc.php.dist dest=/var/www/config/config.inc.php
